export interface WordItem {
  id: string;
  text: string;
  phonemes: string[]; // references phoneme IDs in phonemes.ts
  wave: number;       // Wave/Island number it belongs to
  imageEmoji: string;
  decodable: boolean;
  syllables?: string[]; // optional syllables chunking list (e.g. ['ba', 'na', 'na'])
}

export const words: WordItem[] = [
  // Island 1: Short a (Taught: a, m, s, t, c, r)
  { id: 'cat', text: 'cat', phonemes: ['c', 'a', 't'], wave: 1, imageEmoji: '🐱', decodable: true },
  { id: 'mat', text: 'mat', phonemes: ['m', 'a', 't'], wave: 1, imageEmoji: '🟫', decodable: true },
  { id: 'sat', text: 'sat', phonemes: ['s', 'a', 't'], wave: 1, imageEmoji: '🧘', decodable: true },
  { id: 'rat', text: 'rat', phonemes: ['r', 'a', 't'], wave: 1, imageEmoji: '🐀', decodable: true },
  { id: 'ram', text: 'ram', phonemes: ['r', 'a', 'm'], wave: 1, imageEmoji: '🐏', decodable: true },
  { id: 'tar', text: 'tar', phonemes: ['t', 'a', 'r'], wave: 1, imageEmoji: '🛢️', decodable: true },
  { id: 'car', text: 'car', phonemes: ['c', 'a', 'r'], wave: 1, imageEmoji: '🚗', decodable: true },
  { id: 'mast', text: 'mast', phonemes: ['m', 'a', 's', 't'], wave: 1, imageEmoji: '⛵', decodable: true },
  { id: 'cast', text: 'cast', phonemes: ['c', 'a', 's', 't'], wave: 1, imageEmoji: '🎭', decodable: true },
  { id: 'cram', text: 'cram', phonemes: ['c', 'r', 'a', 'm'], wave: 1, imageEmoji: '🎒', decodable: true },
  { id: 'tram', text: 'tram', phonemes: ['t', 'r', 'a', 'm'], wave: 1, imageEmoji: '🚃', decodable: true },
  { id: 'smart', text: 'smart', phonemes: ['s', 'm', 'a', 'r', 't'], wave: 1, imageEmoji: '🧠', decodable: true },
  { id: 'masts', text: 'masts', phonemes: ['m', 'a', 's', 't', 's'], wave: 1, imageEmoji: '⛵', decodable: true },
  { id: 'trams', text: 'trams', phonemes: ['t', 'r', 'a', 'm', 's'], wave: 1, imageEmoji: '🚃', decodable: true },
  { id: 'crams', text: 'crams', phonemes: ['c', 'r', 'a', 'm', 's'], wave: 1, imageEmoji: '🎒', decodable: true },
  { id: 'scats', text: 'scats', phonemes: ['s', 'c', 'a', 't', 's'], wave: 1, imageEmoji: '🐈', decodable: true },

  // Island 2: Short i / o (Taught: i, o, p, n, d, g + previous)
  { id: 'pig', text: 'pig', phonemes: ['p', 'i', 'g'], wave: 2, imageEmoji: '🐷', decodable: true },
  { id: 'dog', text: 'dog', phonemes: ['d', 'o', 'g'], wave: 2, imageEmoji: '🐶', decodable: true },
  { id: 'pin', text: 'pin', phonemes: ['p', 'i', 'n'], wave: 2, imageEmoji: '📍', decodable: true },
  { id: 'pot', text: 'pot', phonemes: ['p', 'o', 't'], wave: 2, imageEmoji: '🍲', decodable: true },
  { id: 'dig', text: 'dig', phonemes: ['d', 'i', 'g'], wave: 2, imageEmoji: '⛏️', decodable: true },
  { id: 'sad', text: 'sad', phonemes: ['s', 'a', 'd'], wave: 2, imageEmoji: '😢', decodable: true },
  { id: 'robot', text: 'robot', phonemes: ['r', 'o', 'b', 'o', 't'], syllables: ['ro', 'bot'], wave: 2, imageEmoji: '🤖', decodable: true },
  { id: 'dragon', text: 'dragon', phonemes: ['d', 'r', 'a', 'g', 'o', 'n'], syllables: ['dra', 'gon'], wave: 2, imageEmoji: '🐉', decodable: true },
  { id: 'carrot', text: 'carrot', phonemes: ['c', 'a', 'r', 'r', 'o', 't'], syllables: ['car', 'rot'], wave: 2, imageEmoji: '🥕', decodable: true },
  { id: 'pond', text: 'pond', phonemes: ['p', 'o', 'n', 'd'], wave: 2, imageEmoji: '🏞️', decodable: true },
  { id: 'drag', text: 'drag', phonemes: ['d', 'r', 'a', 'g'], wave: 2, imageEmoji: '🚜', decodable: true },
  { id: 'drop', text: 'drop', phonemes: ['d', 'r', 'o', 'p'], wave: 2, imageEmoji: '💧', decodable: true },
  { id: 'snip', text: 'snip', phonemes: ['s', 'n', 'i', 'p'], wave: 2, imageEmoji: '✂️', decodable: true },
  { id: 'snap', text: 'snap', phonemes: ['s', 'n', 'a', 'p'], wave: 2, imageEmoji: '🫰', decodable: true },
  { id: 'drip', text: 'drip', phonemes: ['d', 'r', 'i', 'p'], wave: 2, imageEmoji: '💧', decodable: true },
  { id: 'crop', text: 'crop', phonemes: ['c', 'r', 'o', 'p'], wave: 2, imageEmoji: '🌾', decodable: true },
  { id: 'trap', text: 'trap', phonemes: ['t', 'r', 'a', 'p'], wave: 2, imageEmoji: '🪤', decodable: true },
  { id: 'trip', text: 'trip', phonemes: ['t', 'r', 'i', 'p'], wave: 2, imageEmoji: '🧳', decodable: true },
  { id: 'ponds', text: 'ponds', phonemes: ['p', 'o', 'n', 'd', 's'], wave: 2, imageEmoji: '🏞️', decodable: true },
  { id: 'drags', text: 'drags', phonemes: ['d', 'r', 'a', 'g', 's'], wave: 2, imageEmoji: '🚜', decodable: true },
  { id: 'drops', text: 'drops', phonemes: ['d', 'r', 'o', 'p', 's'], wave: 2, imageEmoji: '💧', decodable: true },
  { id: 'drips', text: 'drips', phonemes: ['d', 'r', 'i', 'p', 's'], wave: 2, imageEmoji: '💧', decodable: true },
  { id: 'crops', text: 'crops', phonemes: ['c', 'r', 'o', 'p', 's'], wave: 2, imageEmoji: '🌾', decodable: true },
  { id: 'traps', text: 'traps', phonemes: ['t', 'r', 'a', 'p', 's'], wave: 2, imageEmoji: '🪤', decodable: true },
  { id: 'trips', text: 'trips', phonemes: ['t', 'r', 'i', 'p', 's'], wave: 2, imageEmoji: '🧳', decodable: true },
  { id: 'picnic', text: 'picnic', phonemes: ['p', 'i', 'c', 'n', 'i', 'c'], syllables: ['pic', 'nic'], wave: 2, imageEmoji: '🧺', decodable: true },
  { id: 'parrots', text: 'parrots', phonemes: ['p', 'a', 'r', 'r', 'o', 't', 's'], syllables: ['par', 'rots'], wave: 2, imageEmoji: '🦜', decodable: true },
  { id: 'dragons', text: 'dragons', phonemes: ['d', 'r', 'a', 'g', 'o', 'n', 's'], syllables: ['dra', 'gons'], wave: 2, imageEmoji: '🐉', decodable: true },
  { id: 'carrots', text: 'carrots', phonemes: ['c', 'a', 'r', 'r', 'o', 't', 's'], syllables: ['car', 'rots'], wave: 2, imageEmoji: '🥕', decodable: true },

  // Island 3: Short e / u (Taught: e, u, f, h, l, b + A-Z + previous)
  { id: 'bed', text: 'bed', phonemes: ['b', 'e', 'd'], wave: 3, imageEmoji: '🛏️', decodable: true },
  { id: 'cup', text: 'cup', phonemes: ['c', 'u', 'p'], wave: 3, imageEmoji: '🥛', decodable: true },
  { id: 'fog', text: 'fog', phonemes: ['f', 'o', 'g'], wave: 3, imageEmoji: '🌫️', decodable: true },
  { id: 'hat', text: 'hat', phonemes: ['h', 'a', 't'], wave: 3, imageEmoji: '🎩', decodable: true },
  { id: 'bug', text: 'bug', phonemes: ['b', 'u', 'g'], wave: 3, imageEmoji: '🐞', decodable: true },
  { id: 'leg', text: 'leg', phonemes: ['l', 'e', 'g'], wave: 3, imageEmoji: '🦵', decodable: true },
  { id: 'banana', text: 'banana', phonemes: ['b', 'a', 'n', 'a', 'n', 'a'], syllables: ['ba', 'na', 'na'], wave: 3, imageEmoji: '🍌', decodable: true },
  { id: 'potato', text: 'potato', phonemes: ['p', 'o', 't', 'a', 't', 'o'], syllables: ['po', 'ta', 'to'], wave: 3, imageEmoji: '🥔', decodable: true },
  { id: 'sunset', text: 'sunset', phonemes: ['s', 'u', 'n', 's', 'e', 't'], syllables: ['sun', 'set'], wave: 3, imageEmoji: '🌅', decodable: true },
  { id: 'pumpkin', text: 'pumpkin', phonemes: ['p', 'u', 'm', 'p', 'k', 'i', 'n'], syllables: ['pump', 'kin'], wave: 3, imageEmoji: '🎃', decodable: true },
  { id: 'dinosaur', text: 'dinosaur', phonemes: ['d', 'i', 'n', 'o', 's', 'a', 'u', 'r'], syllables: ['di', 'no', 'saur'], wave: 3, imageEmoji: '🦕', decodable: true },
  { id: 'astronaut', text: 'astronaut', phonemes: ['a', 's', 't', 'r', 'o', 'n', 'a', 'u', 't'], syllables: ['as', 'tro', 'naut'], wave: 3, imageEmoji: '🧑‍🚀', decodable: true },
  { id: 'blanket', text: 'blanket', phonemes: ['b', 'l', 'a', 'n', 'k', 'e', 't'], syllables: ['blan', 'ket'], wave: 3, imageEmoji: '🛌', decodable: true },
  { id: 'helmet', text: 'helmet', phonemes: ['h', 'e', 'l', 'm', 'e', 't'], syllables: ['hel', 'met'], wave: 3, imageEmoji: '🪖', decodable: true },
  { id: 'dentist', text: 'dentist', phonemes: ['d', 'e', 'n', 't', 'i', 's', 't'], syllables: ['den', 'tist'], wave: 3, imageEmoji: '🦷', decodable: true },
  { id: 'handbag', text: 'handbag', phonemes: ['h', 'a', 'n', 'd', 'b', 'a', 'g'], syllables: ['hand', 'bag'], wave: 3, imageEmoji: '👜', decodable: true },
  { id: 'handbags', text: 'handbags', phonemes: ['h', 'a', 'n', 'd', 'b', 'a', 'g', 's'], syllables: ['hand', 'bags'], wave: 3, imageEmoji: '👜', decodable: true },
  { id: 'helmets', text: 'helmets', phonemes: ['h', 'e', 'l', 'm', 'e', 't', 's'], syllables: ['hel', 'mets'], wave: 3, imageEmoji: '🪖', decodable: true },
  { id: 'blankets', text: 'blankets', phonemes: ['b', 'l', 'a', 'n', 'k', 'e', 't', 's'], syllables: ['blan', 'kets'], wave: 3, imageEmoji: '🛌', decodable: true },
  { id: 'dentists', text: 'dentists', phonemes: ['d', 'e', 'n', 't', 'i', 's', 't', 's'], syllables: ['den', 'tists'], wave: 3, imageEmoji: '🦷', decodable: true },
  { id: 'pumpkins', text: 'pumpkins', phonemes: ['p', 'u', 'm', 'p', 'k', 'i', 'n', 's'], syllables: ['pump', 'kins'], wave: 3, imageEmoji: '🎃', decodable: true },
  { id: 'cobwebs', text: 'cobwebs', phonemes: ['c', 'o', 'b', 'w', 'e', 'b', 's'], syllables: ['cob', 'webs'], wave: 3, imageEmoji: '🕸️', decodable: true },
  { id: 'hotdogs', text: 'hotdogs', phonemes: ['h', 'o', 't', 'd', 'o', 'g', 's'], syllables: ['hot', 'dogs'], wave: 3, imageEmoji: '🌭', decodable: true },
  { id: 'sandbox', text: 'sandbox', phonemes: ['s', 'a', 'n', 'd', 'b', 'o', 'x'], syllables: ['sand', 'box'], wave: 3, imageEmoji: '🏖️', decodable: true },

  // Island 4: Blends (Taught: fl, gr, st, sp + previous)
  { id: 'flat', text: 'flat', phonemes: ['fl', 'a', 't'], wave: 4, imageEmoji: '🥞', decodable: true },
  { id: 'grin', text: 'grin', phonemes: ['gr', 'i', 'n'], wave: 4, imageEmoji: '😀', decodable: true },
  { id: 'stop', text: 'stop', phonemes: ['st', 'o', 'p'], wave: 4, imageEmoji: '🛑', decodable: true },
  { id: 'spin', text: 'spin', phonemes: ['sp', 'i', 'n'], wave: 4, imageEmoji: '🌀', decodable: true },
  { id: 'monster', text: 'monster', phonemes: ['m', 'o', 'n', 'st', 'e', 'r'], syllables: ['mon', 'ster'], wave: 4, imageEmoji: '👾', decodable: true },
  { id: 'spider', text: 'spider', phonemes: ['sp', 'i', 'd', 'e', 'r'], syllables: ['spi', 'der'], wave: 4, imageEmoji: '🕷️', decodable: true },
  { id: 'forest', text: 'forest', phonemes: ['f', 'o', 'r', 'e', 'st'], syllables: ['for', 'est'], wave: 4, imageEmoji: '🌲', decodable: true },
  { id: 'stamp', text: 'stamp', phonemes: ['st', 'a', 'm', 'p'], wave: 4, imageEmoji: '💌', decodable: true },
  { id: 'stand', text: 'stand', phonemes: ['st', 'a', 'n', 'd'], wave: 4, imageEmoji: '🧍', decodable: true },
  { id: 'stamps', text: 'stamps', phonemes: ['st', 'a', 'm', 'p', 's'], wave: 4, imageEmoji: '💌', decodable: true },
  { id: 'stands', text: 'stands', phonemes: ['st', 'a', 'n', 'd', 's'], wave: 4, imageEmoji: '🧍', decodable: true },
  { id: 'forests', text: 'forests', phonemes: ['f', 'o', 'r', 'e', 'st', 's'], syllables: ['for', 'ests'], wave: 4, imageEmoji: '🌲', decodable: true },
  { id: 'monsters', text: 'monsters', phonemes: ['m', 'o', 'n', 'st', 'e', 'r', 's'], syllables: ['mon', 'sters'], wave: 4, imageEmoji: '👾', decodable: true },
  { id: 'flower', text: 'flower', phonemes: ['fl', 'o', 'w', 'e', 'r'], syllables: ['flow', 'er'], wave: 4, imageEmoji: '🌸', decodable: true },
  { id: 'flowers', text: 'flowers', phonemes: ['fl', 'o', 'w', 'e', 'r', 's'], syllables: ['flow', 'ers'], wave: 4, imageEmoji: '🌸', decodable: true },
  { id: 'grumpy', text: 'grumpy', phonemes: ['gr', 'u', 'm', 'p', 'y'], syllables: ['grum', 'py'], wave: 4, imageEmoji: '😠', decodable: true },
  { id: 'grandpa', text: 'grandpa', phonemes: ['gr', 'a', 'n', 'd', 'p', 'a'], syllables: ['grand', 'pa'], wave: 4, imageEmoji: '👴', decodable: true },
  { id: 'grandpas', text: 'grandpas', phonemes: ['gr', 'a', 'n', 'd', 'p', 'a', 's'], syllables: ['grand', 'pas'], wave: 4, imageEmoji: '👴', decodable: true },
  { id: 'gravity', text: 'gravity', phonemes: ['gr', 'a', 'v', 'i', 't', 'y'], syllables: ['grav', 'i', 'ty'], wave: 4, imageEmoji: '🌌', decodable: true },
  { id: 'splendid', text: 'splendid', phonemes: ['sp', 'l', 'e', 'n', 'd', 'i', 'd'], syllables: ['splen', 'did'], wave: 4, imageEmoji: '✨', decodable: true },
  { id: 'standard', text: 'standard', phonemes: ['st', 'a', 'n', 'd', 'a', 'r', 'd'], syllables: ['stan', 'dard'], wave: 4, imageEmoji: '📋', decodable: true },

  // Island 5: Digraphs (Taught: sh, ch, th, ck + previous)
  { id: 'ship', text: 'ship', phonemes: ['sh', 'i', 'p'], wave: 5, imageEmoji: '🚢', decodable: true },
  { id: 'chin', text: 'chin', phonemes: ['ch', 'i', 'n'], wave: 5, imageEmoji: '👤', decodable: true },
  { id: 'thin', text: 'thin', phonemes: ['th', 'i', 'n'], wave: 5, imageEmoji: '📏', decodable: true },
  { id: 'duck', text: 'duck', phonemes: ['d', 'u', 'ck'], wave: 5, imageEmoji: '🦆', decodable: true },
  { id: 'chicken', text: 'chicken', phonemes: ['ch', 'i', 'ck', 'e', 'n'], syllables: ['chick', 'en'], wave: 5, imageEmoji: '🐔', decodable: true },
  { id: 'children', text: 'children', phonemes: ['ch', 'i', 'l', 'd', 'r', 'e', 'n'], syllables: ['chil', 'dren'], wave: 5, imageEmoji: '🧑‍🤝‍🧑', decodable: true },
  { id: 'thunder', text: 'thunder', phonemes: ['th', 'u', 'n', 'd', 'e', 'r'], syllables: ['thun', 'der'], wave: 5, imageEmoji: '⚡', decodable: true },
  { id: 'pocket', text: 'pocket', phonemes: ['p', 'o', 'ck', 'e', 't'], syllables: ['poc', 'ket'], wave: 5, imageEmoji: '🪙', decodable: true },
  { id: 'ostrich', text: 'ostrich', phonemes: ['o', 's', 't', 'r', 'i', 'ch'], syllables: ['os', 'trich'], wave: 5, imageEmoji: '🦤', decodable: true },
  { id: 'chickens', text: 'chickens', phonemes: ['ch', 'i', 'ck', 'e', 'n', 's'], syllables: ['chick', 'ens'], wave: 5, imageEmoji: '🐔', decodable: true },
  { id: 'thunders', text: 'thunders', phonemes: ['th', 'u', 'n', 'd', 'e', 'r', 's'], syllables: ['thun', 'ders'], wave: 5, imageEmoji: '⚡', decodable: true },
  { id: 'pockets', text: 'pockets', phonemes: ['p', 'o', 'ck', 'e', 't', 's'], syllables: ['poc', 'kets'], wave: 5, imageEmoji: '🪙', decodable: true },
  { id: 'shocking', text: 'shocking', phonemes: ['sh', 'o', 'ck', 'i', 'n', 'g'], syllables: ['shock', 'ing'], wave: 5, imageEmoji: '⚡', decodable: true },
  { id: 'backpack', text: 'backpack', phonemes: ['b', 'a', 'ck', 'p', 'a', 'ck'], syllables: ['back', 'pack'], wave: 5, imageEmoji: '🎒', decodable: true },
  { id: 'duckling', text: 'duckling', phonemes: ['d', 'u', 'ck', 'l', 'i', 'n', 'g'], syllables: ['duck', 'ling'], wave: 5, imageEmoji: '🐥', decodable: true },

  // Island 6: Magic e (Taught: a_e, i_e, o_e + previous)
  { id: 'cake', text: 'cake', phonemes: ['c', 'a_e', 'k'], wave: 6, imageEmoji: '🍰', decodable: true },
  { id: 'lake', text: 'lake', phonemes: ['l', 'a_e', 'k'], wave: 6, imageEmoji: '🌊', decodable: true },
  { id: 'gate', text: 'gate', phonemes: ['g', 'a_e', 't'], wave: 6, imageEmoji: '🚪', decodable: true },
  { id: 'late', text: 'late', phonemes: ['l', 'a_e', 't'], wave: 6, imageEmoji: '⏰', decodable: true },
  { id: 'game', text: 'game', phonemes: ['g', 'a_e', 'm'], wave: 6, imageEmoji: '🎮', decodable: true },
  { id: 'tame', text: 'tame', phonemes: ['t', 'a_e', 'm'], wave: 6, imageEmoji: '🦁', decodable: true },
  { id: 'pine', text: 'pine', phonemes: ['p', 'i_e', 'n'], wave: 6, imageEmoji: '🌲', decodable: true },
  { id: 'line', text: 'line', phonemes: ['l', 'i_e', 'n'], wave: 6, imageEmoji: '➖', decodable: true },
  { id: 'nine', text: 'nine', phonemes: ['n', 'i_e', 'n'], wave: 6, imageEmoji: '9️⃣', decodable: true },
  { id: 'fine', text: 'fine', phonemes: ['f', 'i_e', 'n'], wave: 6, imageEmoji: '👌', decodable: true },
  { id: 'home', text: 'home', phonemes: ['h', 'o_e', 'm'], wave: 6, imageEmoji: '🏠', decodable: true },
  { id: 'hope', text: 'hope', phonemes: ['h', 'o_e', 'p'], wave: 6, imageEmoji: '🤞', decodable: true },
  { id: 'cone', text: 'cone', phonemes: ['c', 'o_e', 'n'], wave: 6, imageEmoji: '🍦', decodable: true },
  { id: 'bone', text: 'bone', phonemes: ['b', 'o_e', 'n'], wave: 6, imageEmoji: '🦴', decodable: true },
  { id: 'coke', text: 'coke', phonemes: ['c', 'o_e', 'k'], wave: 6, imageEmoji: '🥤', decodable: true },
  { id: 'pancake', text: 'pancake', phonemes: ['p', 'a', 'n', 'c', 'a_e', 'k'], syllables: ['pan', 'cake'], wave: 6, imageEmoji: '🥞', decodable: true },
  { id: 'pancakes', text: 'pancakes', phonemes: ['p', 'a', 'n', 'c', 'a_e', 'k', 's'], syllables: ['pan', 'cakes'], wave: 6, imageEmoji: '🥞', decodable: true },
  { id: 'sunshine', text: 'sunshine', phonemes: ['s', 'u', 'n', 'sh', 'i_e', 'n'], syllables: ['sun', 'shine'], wave: 6, imageEmoji: '☀️', decodable: true },
  { id: 'campfire', text: 'campfire', phonemes: ['c', 'a', 'm', 'p', 'f', 'i_e', 'r'], syllables: ['camp', 'fire'], wave: 6, imageEmoji: '🔥', decodable: true },
  { id: 'envelope', text: 'envelope', phonemes: ['e', 'n', 'v', 'e', 'l', 'o_e', 'p'], syllables: ['en', 'vel', 'ope'], wave: 6, imageEmoji: '✉️', decodable: true },
  { id: 'reptiles', text: 'reptiles', phonemes: ['r', 'e', 'p', 't', 'i_e', 'l', 's'], syllables: ['rep', 'tiles'], wave: 6, imageEmoji: '🦎', decodable: true },
  { id: 'homesick', text: 'homesick', phonemes: ['h', 'o_e', 'm', 's', 'i', 'ck'], syllables: ['home', 'sick'], wave: 6, imageEmoji: '🏠', decodable: true },
  { id: 'cupcakes', text: 'cupcakes', phonemes: ['c', 'u', 'p', 'c', 'a_e', 'k', 's'], syllables: ['cup', 'cakes'], wave: 6, imageEmoji: '🧁', decodable: true },
  { id: 'tadpoles', text: 'tadpoles', phonemes: ['t', 'a', 'd', 'p', 'o_e', 'l', 's'], syllables: ['tad', 'poles'], wave: 6, imageEmoji: '🐸', decodable: true },

  // Island 7: Heart words (Irregular sight words)
  { id: 'the', text: 'the', phonemes: ['the'], wave: 7, imageEmoji: '👉', decodable: false },
  { id: 'said', text: 'said', phonemes: ['said'], wave: 7, imageEmoji: '💬', decodable: false },
  { id: 'was', text: 'was', phonemes: ['was'], wave: 7, imageEmoji: '⏳', decodable: false }
];
